services:
  - type: web
    name: resume-craft
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir backend app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
